services:
  postgres:
    image: pgvector/pgvector:0.8.1-pg18-trixie
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

      APP_USER: ${ATLAS_USER}
      APP_DB: ${ATLAS_DB_NAME}
      APP_PASSWORD: ${ATLAS_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql
      # This is the magic part:
      - ./db-init:/docker-entrypoint-initdb.d
    ports:
      - "${POSTGRES_PORT}:5432"

  # Since you're using NextJS & Prisma, you might want a GUI for the DB too
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${ADMIN_PASSWORD}
    ports:
      - "5050:80"

  atlas-web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: atlas-web
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL_DOCKER}
      - AUTH_SECRET=${AUTH_SECRET}
      - AUTH_GITHUB_ID=${AUTH_GITHUB_ID}
      - AUTH_GITHUB_SECRET=${AUTH_GITHUB_SECRET}
      - AUTH_TRUST_HOST=true
      - AUTH_URL=http://localhost:3000
    depends_on:
      - postgres

volumes:
  postgres_data:
